-- 코드를 입력하세요
SELECT I.FLAVOR
FROM
    FIRST_HALF AS F
    JOIN ICECREAM_INFO AS I ON F.FLAVOR = I.FLAVOR
WHERE
    I.INGREDIENT_TYPE = 'fruit_based'
GROUP BY
    I.FLAVOR
HAVING
    SUM(F.TOTAL_ORDER) > 3000
ORDER BY SUM(F.TOTAL_ORDER) DESC;