-- 코드를 입력하세요
SELECT EXTRACT(
        YEAR
        FROM OS.SALES_DATE
    ) AS YEAR, EXTRACT(
        MONTH
        FROM OS.SALES_DATE
    ) AS MONTH, UI.GENDER AS GENDER, COUNT(DISTINCT UI.USER_ID) AS USERS
FROM
    ONLINE_SALE AS OS
    INNER JOIN USER_INFO AS UI ON OS.USER_ID = UI.USER_ID
WHERE
    UI.GENDER IS NOT NULL
GROUP BY
    YEAR,
    MONTH,
    GENDER
ORDER BY YEAR, MONTH, GENDER ASC;