-- 코드를 작성해주세요
WITH RECURSIVE
    GENERATION AS (
        SELECT ID, 1 AS GENERATION_LEVEL
        FROM ECOLI_DATA
        WHERE
            PARENT_ID IS NULL
        UNION
        SELECT E.ID, G.GENERATION_LEVEL + 1 AS GENERATION_LEVEL
        FROM ECOLI_DATA AS E
            INNER JOIN GENERATION AS G ON E.PARENT_ID = G.ID
    )

SELECT
    COUNT(*) AS COUNT,
    GENERATION_LEVEL AS GENERATION
FROM GENERATION AS G
    LEFT OUTER JOIN ECOLI_DATA AS E ON G.ID = E.PARENT_ID
WHERE
    E.ID IS NULL
GROUP BY
    GENERATION_LEVEL
ORDER BY GENERATION_LEVEL;