-- 코드를 작성해주세요
WITH
    MAX_LENGTH AS (
        SELECT FNI.FISH_TYPE, FNI.FISH_NAME, MAX(FI.LENGTH) AS MAX_LENGTH
        FROM
            FISH_INFO AS FI
            INNER JOIN FISH_NAME_INFO AS FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
        GROUP BY
            FNI.FISH_TYPE,
            FNI.FISH_NAME
    )

SELECT FI.ID, ML.FISH_NAME, ML.MAX_LENGTH AS LENGTH
FROM FISH_INFO AS FI
    INNER JOIN MAX_LENGTH AS ML ON FI.FISH_TYPE = ML.FISH_TYPE
WHERE
    FI.LENGTH = ML.MAX_LENGTH
ORDER BY FI.ID ASC;