-- 코드를 작성해주세요
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM (
        SELECT T.ITEM_ID, T.PARENT_ITEM_ID, I.ITEM_NAME, I.RARITY
        FROM ITEM_TREE AS T
            JOIN ITEM_INFO AS I ON T.ITEM_ID = I.ITEM_ID
    ) AS A
    JOIN ITEM_INFO AS I ON A.PARENT_ITEM_ID = I.ITEM_ID
    AND I.RARITY = 'RARE'
ORDER BY ITEM_ID DESC;