-- 코드를 작성해주세요
WITH
    YEAR_MAX_SIZE AS (
        SELECT EXTRACT(
                YEAR
                FROM DIFFERENTIATION_DATE
            ) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
        FROM ECOLI_DATA
        GROUP BY
            YEAR
    )

SELECT YMS.YEAR, (
        YMS.MAX_SIZE - E.SIZE_OF_COLONY
    ) AS YEAR_DEV, E.ID
FROM
    ECOLI_DATA AS E
    INNER JOIN YEAR_MAX_SIZE AS YMS ON EXTRACT(
        YEAR
        FROM E.DIFFERENTIATION_DATE
    ) = YMS.YEAR
ORDER BY YMS.YEAR ASC, YEAR_DEV ASC;