-- 코드를 입력하세요
WITH RECURSIVE
    HOURS AS (
        SELECT 0 AS HOUR
        UNION ALL
        SELECT HOUR + 1
        FROM HOURS
        WHERE
            HOUR <= 22
    )

SELECT HS.HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM HOURS AS HS
    LEFT OUTER JOIN ANIMAL_OUTS AS AO ON HS.HOUR = EXTRACT(
        HOUR
        FROM AO.DATETIME
    )
GROUP BY
    HOUR
ORDER BY HOUR ASC;